In [1]:
# Dependencies
import pandas as pd

In [2]:
csvpath1 = 'Resources/all-states-history.csv'
States_df = pd.read_csv(csvpath1)
States_df

,date,state,dataQualityGrade,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2021-02-08,AK,A,279.0,NaN,0,NaN,1219.0,1219.0,39.0,...,1555532.0,18621,NaN,NaN,NaN,NaN,NaN,0,1555532.0,18621
1,2021-02-08,AL,A,8523.0,6753.0,8,1770.0,43383.0,43383.0,1524.0,...,2191851.0,4522,NaN,NaN,109716.0,NaN,2191851.0,4522,NaN,0
2,2021-02-08,AR,A+,5106.0,4081.0,30,1025.0,14099.0,14099.0,777.0,...,2535155.0,5830,NaN,NaN,NaN,391322.0,NaN,0,2535155.0,5830
3,2021-02-08,AS,NaN,0.0,NaN,0,NaN,NaN,NaN,NaN,...,2140.0,0,NaN,NaN,NaN,NaN,NaN,0,2140.0,0
4,2021-02-08,AZ,A+,14055.0,12487.0,7,1568.0,54713.0,54713.0,2853.0,...,6993662.0,11514,423799.0,NaN,NaN,NaN,3552101.0,3708,6993662.0,11514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19256,2020-01-17,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
19257,2020-01-16,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
19258,2020-01-15,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
19259,2020-01-14,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
19260,2020-01-13,WA,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [43]:
filtered_States_df = States_df[['state','date','positive','death']]
renamed_States_df = filtered_States_df.rename(columns={'state':'State', 'date':'Date',
                                                       'positive':'Cumulative Cases', 
                                                       'death':'Cumulative Deaths'})
grouped_States_df = cleaned_States_df.groupby('State')
latest_States_df = grouped_States_df.max()
latest_States_df
lowest_cases = latest_States_df.loc['VT', 'Cumulative Cases']
cleaned_States_df = latest_States_df.loc[latest_States_df['Cumulative Cases'] >= lowest_state]
cleaned_States_df

             Date  Cumulative Cases  Cumulative Deaths
State
AK     2021-02-08           53694.0              279.0
AL     2021-02-08          473348.0             8523.0
AR     2021-02-08          307373.0             5106.0
AZ     2021-02-08          782887.0            14055.0
CA     2021-02-08         3346340.0            44150.0
CO     2021-02-08          406276.0             5733.0
CT     2021-02-08          263739.0             7282.0
DC     2021-02-08           38136.0              956.0
DE     2021-02-08           80931.0             1208.0
FL     2021-02-08         1751343.0            28287.0
GA     2021-02-08          943695.0            15130.0
HI     2021-02-08           27195.0              418.0
IA     2021-02-08          271698.0             5110.0
ID     2021-02-08          165209.0             1767.0
IL     2021-02-08         1148088.0            21779.0
IN     2021-02-08          640744.0            11875.0
KS     2021-02-08          282960.0             4197.0
KY     2021-02-08          378793.0             4091.0
LA     2021-02-08          412989.0             9142.0
MA     2021-02-08          545303.0            15054.0
MD     2021-02-08          364553.0             7372.0
ME     2021-02-08           41419.0              636.0
MI     2021-02-08          622813.0            15863.0
MN     2021-02-08          468682.0             6302.0
MO     2021-02-08          466664.0             7143.0
MS     2021-02-08          282313.0             6270.0
MT     2021-02-08           95914.0             1314.0
NC     2021-02-08          799279.0             9991.0
ND     2021-02-08           98184.0             1454.0
NE     2021-02-08          193826.0             1968.0
NH     2021-02-08           68499.0             1106.0
NJ     2021-02-08          724728.0            22011.0
NM     2021-02-08          177867.0             3412.0
NV     2021-02-08          284590.0             4522.0
NY     2021-02-08         1479220.0            36339.0
OH     2021-02-08          922143.0            11695.0
OK     2021-02-08          404994.0             3817.0
OR     2021-02-08          147122.0             2023.0
PA     2021-02-08          872825.0            22471.0
PR     2021-02-08           96161.0             1888.0
RI     2021-02-08          119104.0             2236.0
SC     2021-02-08          468403.0             7690.0
SD     2021-02-08          109283.0             1809.0
TN     2021-02-08          745826.0            10566.0
TX     2021-02-08         2491227.0            38700.0
UT     2021-02-08          355122.0             1738.0
VA     2021-02-08          530825.0             6820.0
VT     2021-02-08           13046.0              183.0
WA     2021-02-08          320146.0             4449.0
WI     2021-02-08          601391.0             6614.0
WV     2021-02-08          125106.0             2131.0
WY     2021-02-08           52784.0              624.0

In [45]:
cleaned_States_df.to_csv('Output/StatesCases.csv')